# Generated by Django 5.0.1 on 2024-09-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0015_delete_recordssubscriptionplan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='plan_name',
        ),
        migrations.AddField(
            model_name='subscription',
            name='locked_plan_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
